SELECT
		 C_CUSTKEY
		,C_NAME
		,SUM(l_extendedprice*(1-l_discount))		AS REVENUE
		,C_ACCTBAL
		,n_name
		,C_ADDRESS
		,C_PHONE
		,C_COMMENT
	FROM
		 CUSTOMER
		,ORDERS
		,LINEITEM
		,NATION
	WHERE
		 C_CUSTKEY		= O_CUSTKEY
	AND	 L_ORDERKEY		= O_ORDERKEY
	AND	 O_ORDERDATE		>= DATE '1994-05-01'
	AND	 O_ORDERDATE		< DATE '1994-05-01' + INTERVAL '3' MONTH
	AND	 L_RETURNFLAG		= 'R'
	AND	 C_NATIONKEY		= N_NATIONKEY
	GROUP BY
		 C_CUSTKEY
		,C_NAME
		,C_ACCTBAL
		,C_PHONE
		,n_name
		,C_ADDRESS
		,C_COMMENT
	ORDER BY
		 REVENUE	DESC
	LIMIT 20;
