SELECT
		 PS_PARTKEY
		,SUM(PS_SUPPLYCOST*PS_AVAILQTY)		AS VALUE
	FROM
		 PARTSUPP
		,SUPPLIER
		,NATION
	WHERE
		 PS_SUPPKEY		= S_SUPPKEY
	AND	 S_NATIONKEY		= N_NATIONKEY
	AND	 n_name			= N'GERMANY'
	GROUP BY
		 PS_PARTKEY
	HAVING
		 SUM(PS_SUPPLYCOST*PS_AVAILQTY) >
			(
			 SELECT
					 SUM(PS_SUPPLYCOST*PS_AVAILQTY) * 0.0000010000
				FROM PARTSUPP, SUPPLIER, NATION
				WHERE PS_SUPPKEY = S_SUPPKEY
				AND S_NATIONKEY = N_NATIONKEY
				AND n_name = N'GERMANY'
			)
	ORDER BY
		 VALUE		DESC;
