SELECT
		 P_BRAND
		,p_type
		,P_SIZE
		,COUNT(DISTINCT PS_SUPPKEY)	AS SUPPLIER_CNT
	FROM
		 PARTSUPP
		,PART
	WHERE
		 P_PARTKEY		= PS_PARTKEY
	AND	 P_BRAND <> N'Brand#54'
	AND	 p_type NOT LIKE 'MEDIUM BRUSHED%'
	AND	 P_SIZE IN (5,1, 43, 3, 14, 24, 30, 48)
	AND	 PS_SUPPKEY	NOT IN
			(SELECT		 S_SUPPKEY
				FROM	 SUPPLIER
				WHERE	 S_COMMENT	LIKE '%Customer%Complaints%'
			)
	GROUP BY
		 P_BRAND
		,p_type
		,P_SIZE
	ORDER BY
		 SUPPLIER_CNT		DESC
		,P_BRAND
		,p_type
		,P_SIZE;
