SELECT
		 S_ACCTBAL
		,S_NAME
		,n_name
		,P_PARTKEY
		,P_MFGR
		,S_ADDRESS
		,S_PHONE
		,S_COMMENT
	FROM
		 PART
		,SUPPLIER
		,PARTSUPP
		,NATION
		,REGION
	WHERE
		 P_PARTKEY	= PS_PARTKEY
	AND	 S_SUPPKEY	= PS_SUPPKEY
	AND	 P_SIZE		= 50
	AND	 p_type		LIKE '%NICKEL'
	AND	 S_NATIONKEY	= N_NATIONKEY
	AND	 N_REGIONKEY	= R_REGIONKEY
	AND	 R_NAME		= N'EUROPE'
	AND	 PS_SUPPLYCOST	=
			(
			 SELECT		 MIN(PS_SUPPLYCOST)
				FROM	 PARTSUPP ,SUPPLIER ,NATION ,REGION
				WHERE	 P_PARTKEY	= PS_PARTKEY
				AND	 S_SUPPKEY	= PS_SUPPKEY
				AND	 S_NATIONKEY	= N_NATIONKEY
				AND	 N_REGIONKEY	= R_REGIONKEY
				AND	 R_NAME		= N'EUROPE'
			)
	ORDER BY
		 S_ACCTBAL	DESC
		,n_name
		,S_NAME
		,P_PARTKEY
	LIMIT 100;
