SELECT
		 n_name
		,SUM(l_extendedprice*(1-l_discount))	AS REVENUE
	FROM
		 CUSTOMER
		,ORDERS
		,LINEITEM
		,SUPPLIER
		,NATION
		,REGION
	WHERE
		 C_CUSTKEY		= O_CUSTKEY
	AND	 O_ORDERKEY		= L_ORDERKEY
	AND	 L_SUPPKEY		= S_SUPPKEY
	AND	 C_NATIONKEY		= S_NATIONKEY
	AND	 S_NATIONKEY		= N_NATIONKEY
	AND	 N_REGIONKEY		= R_REGIONKEY
	AND	 R_NAME			= N'EUROPE'
	AND	 O_ORDERDATE		>= DATE '1997-01-01'
	AND	 O_ORDERDATE		< DATE '1997-01-01' + INTERVAL '1' YEAR
	GROUP BY
		 n_name
	ORDER BY
		 REVENUE	DESC;
