SELECT
		 SUPP_NATION
		,CUST_NATION
		,L_YEAR
		,SUM(VOLUME)		AS REVENUE
	FROM
		(
		 SELECT		 N1.n_name			AS SUPP_NATION
				,N2.n_name			AS CUST_NATION
				,EXTRACT(YEAR FROM L_SHIPDATE)	AS L_YEAR
				,l_extendedprice*(1-l_discount)	AS VOLUME
			FROM
				 SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE	 S_SUPPKEY	= L_SUPPKEY
			AND	 O_ORDERKEY	= L_ORDERKEY
			AND	 C_CUSTKEY	= O_CUSTKEY
			AND	 S_NATIONKEY	= N1.N_NATIONKEY
			AND	 C_NATIONKEY	= N2.N_NATIONKEY
			AND	(
				 (N1.n_name	= N'ALGERIA'	AND N2.n_name	= N'RUSSIA')
				OR
				 (N1.n_name	= N'RUSSIA'   AND N2.n_name	= N'ALGERIA')
				)
			AND	 L_SHIPDATE	BETWEEN DATE '1995-01-01' AND DATE '1996-12-31'
		)
								AS SHIPPING
	GROUP BY
		 SUPP_NATION
		,CUST_NATION
		,L_YEAR
	ORDER BY
		 SUPP_NATION
		,CUST_NATION
		,L_YEAR;
