SELECT
		 O_YEAR
		, SUM(CASE WHEN NATION = N'RUSSIA'  THEN VOLUME ELSE 0 END) / SUM(VOLUME)	AS MKT_SHARE
	FROM
		(
		 SELECT
				 EXTRACT(YEAR FROM O_ORDERDATE)		AS O_YEAR
				,l_extendedprice * (1-l_discount)	AS VOLUME
				,N2.n_name				AS NATION
			FROM
				PART, 
				SUPPLIER, 
				LINEITEM, 
				ORDERS, 
				CUSTOMER, 
				NATION N1, 
				NATION N2, 
				REGION
			WHERE
				 P_PARTKEY	= L_PARTKEY
			AND	 S_SUPPKEY	= L_SUPPKEY
			AND	 L_ORDERKEY	= O_ORDERKEY
			AND	 O_CUSTKEY	= C_CUSTKEY
			AND	 C_NATIONKEY	= N1.N_NATIONKEY
			AND	 N1.N_REGIONKEY	= R_REGIONKEY
			AND	 R_NAME		= N'EUROPE'
			AND	 S_NATIONKEY	= N2.N_NATIONKEY
			AND	 O_ORDERDATE	BETWEEN DATE '01-01-95' and DATE '12-31-96'
			AND	 p_type		= N'STANDARD POLISHED TIN'
		)
									ALL_NATIONS
	GROUP BY
		 O_YEAR
	ORDER BY
		 O_YEAR;
